#!/usr/bin/env bash
# This script displays the PID and process name for processes containing "bash" in their name.

for dir in /proc/[0-9]*; do
    if [[ -f "$dir/comm" ]] && grep -q bash "$dir/comm"; then
        pid=${dir##*/}
        echo "PID: /proc/$pid - $(cat "$dir/comm")"
    fi
done
