#!/usr/bin/env bash
# This script kills the 7-highlander process if it is running

process_name="7-highlander"

# Check if the process is running
if pgrep "$process_name" > /dev/null; then
    # Kill the process
    pkill "$process_name"
    echo "Process $process_name killed."
else
    echo "Process $process_name not running."
fi